[project]
name = "rdf-web-course"
version = "0.1.0"
description = "A beginner-friendly web development course created with Material for MkDocs."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mkdocs-material>=9.6.19",
]
